apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nats-data
  namespace: nats
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
