apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nats-monitor-tls
  namespace: nats
spec:
  secretName: nats-monitor-tls
  duration: 8760h
  renewBefore: 720h
  dnsNames:
  - nats-monitor.home.arpa
  issuerRef:
    kind: ClusterIssuer
    name: local-ca
