apiVersion: v1
kind: Secret
metadata:
  name: coder-db-url
  namespace: coder
type: Opaque
stringData:
  # IMPORTANTE: Ajuste para seu ambiente homelab
  # Formato: postgres://usuario:senha@host:porta/database?sslmode=disable
  # Para homelab, geralmente sslmode=disable é mais simples
  url: "postgres://coder_user:sua_senha@<DB_HOST>:5432/coder?sslmode=disable" # Substitua <DB_HOST> pelo IP ou hostname do seu banco de dados. Se o DB estiver no cluster, use o nome do serviço (ex: postgresql.default.svc.cluster.local)