apiVersion: velero.io/v1
kind: Backup
metadata:
  name: full-cluster-backup
  namespace: velero
  labels:
    backup-type: manual
    backup-scope: cluster
spec:
  includedNamespaces:
  - '*'
  excludedNamespaces:
  - velero
  - kube-system
  - kube-public
  - kube-node-lease
  includedResources:
  - '*'
  excludedResources:
  - events
  - events.events.k8s.io
  - backups.velero.io
  - restores.velero.io
  - resticrepositories.velero.io
  labelSelector: {}
  storageLocation: default
  volumeSnapshotLocations:
  - default
  ttl: 720h  # 30 dias
  hooks:
    resources:
    - name: pre-backup-hook
      includedNamespaces:
      - monitoring
      - production
      labelSelector:
        matchLabels:
          backup-hook: enabled
      pre:
      - exec:
          container: app
          command:
          - /bin/sh
          - -c
          - |
            echo "Iniciando backup..."
            # Comandos para preparar a aplicação para backup
            # Exemplo: flush de caches, pausar escritas, etc.

---
apiVersion: velero.io/v1
kind: Backup
metadata:
  name: monitoring-backup
  namespace: velero
  labels:
    backup-type: scheduled
    backup-scope: monitoring
spec:
  includedNamespaces:
  - monitoring
  includedResources:
  - '*'
  excludedResources:
  - events
  - events.events.k8s.io
  labelSelector:
    matchLabels:
      backup: enabled
  storageLocation: default
  volumeSnapshotLocations:
  - default
  ttl: 168h  # 7 dias

---
apiVersion: velero.io/v1
kind: Backup
metadata:
  name: production-backup
  namespace: velero
  labels:
    backup-type: scheduled
    backup-scope: production
spec:
  includedNamespaces:
  - production
  includedResources:
  - '*'
  excludedResources:
  - events
  - events.events.k8s.io
  labelSelector:
    matchLabels:
      backup: enabled
  storageLocation: default
  volumeSnapshotLocations:
  - default
  ttl: 720h  # 30 dias
  hooks:
    resources:
    - name: database-backup-hook
      includedNamespaces:
      - production
      labelSelector:
        matchLabels:
          app: database
      pre:
      - exec:
          container: database
          command:
          - /bin/sh
          - -c
          - |
            echo "Criando backup do banco de dados..."
            # Comandos específicos para backup do banco de dados
            # Exemplo: pg_dump, mysqldump, etc.
            pg_dump -U postgres mydb > /backup/database-backup.sql

---
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: daily-cluster-backup
  namespace: velero
  labels:
    backup-type: scheduled
    backup-schedule: daily
spec:
  schedule: "0 2 * * *"  # 2 AM todos os dias
  template:
    includedNamespaces:
    - default
    - monitoring
    - production
    excludedResources:
    - events
    - events.events.k8s.io
    storageLocation: default
    volumeSnapshotLocations:
    - default
    ttl: 720h  # 30 dias

---
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: hourly-monitoring-backup
  namespace: velero
  labels:
    backup-type: scheduled
    backup-schedule: hourly
spec:
  schedule: "0 * * * *"  # A cada hora
  template:
    includedNamespaces:
    - monitoring
    excludedResources:
    - events
    - events.events.k8s.io
    storageLocation: default
    volumeSnapshotLocations:
    - default
    ttl: 24h  # 1 dia