apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"StatefulSet","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"messaging","app.kubernetes.io/name":"rabbitmq"},"name":"rabbitmq","namespace":"rabbitmq"},"spec":{"replicas":3,"selector":{"matchLabels":{"app.kubernetes.io/name":"rabbitmq"}},"serviceName":"rabbitmq-headless","template":{"metadata":{"annotations":{"prometheus.io/path":"/metrics","prometheus.io/port":"15692","prometheus.io/scrape":"true"},"labels":{"app.kubernetes.io/component":"messaging","app.kubernetes.io/name":"rabbitmq"}},"spec":{"affinity":{"podAntiAffinity":{"preferredDuringSchedulingIgnoredDuringExecution":[{"podAffinityTerm":{"labelSelector":{"matchExpressions":[{"key":"app.kubernetes.io/name","operator":"In","values":["rabbitmq"]}]},"topologyKey":"kubernetes.io/hostname"},"weight":100}]}},"containers":[{"env":[{"name":"MY_POD_NAME","valueFrom":{"fieldRef":{"fieldPath":"metadata.name"}}},{"name":"MY_POD_NAMESPACE","valueFrom":{"fieldRef":{"fieldPath":"metadata.namespace"}}},{"name":"RABBITMQ_DEFAULT_USER","valueFrom":{"secretKeyRef":{"key":"username","name":"rabbitmq-admin"}}},{"name":"RABBITMQ_DEFAULT_PASS","valueFrom":{"secretKeyRef":{"key":"password","name":"rabbitmq-admin"}}},{"name":"RABBITMQ_ERLANG_COOKIE","valueFrom":{"secretKeyRef":{"key":"cookie","name":"rabbitmq-admin"}}},{"name":"RABBITMQ_USE_LONGNAME","value":"true"},{"name":"K8S_SERVICE_NAME","value":"rabbitmq-headless"},{"name":"RABBITMQ_ENABLED_PLUGINS_FILE","value":"/etc/rabbitmq/enabled_plugins"},{"name":"RABBITMQ_CONFIG_FILE","value":"/etc/rabbitmq/rabbitmq.conf"},{"name":"RABBITMQ_LOGS","value":"/var/log/rabbitmq/rabbitmq.log"},{"name":"RABBITMQ_SASL_LOGS","value":"/var/log/rabbitmq/rabbitmq-sasl.log"}],"image":"rabbitmq:3.12.12-management-alpine","imagePullPolicy":"IfNotPresent","lifecycle":{"preStop":{"exec":{"command":["rabbitmqctl","stop_app"]}}},"name":"rabbitmq","ports":[{"containerPort":5672,"name":"amqp","protocol":"TCP"},{"containerPort":5671,"name":"amqp-ssl","protocol":"TCP"},{"containerPort":15672,"name":"management","protocol":"TCP"},{"containerPort":15671,"name":"management-ssl","protocol":"TCP"},{"containerPort":15692,"name":"prometheus","protocol":"TCP"},{"containerPort":15691,"name":"prometheus-ssl","protocol":"TCP"},{"containerPort":4369,"name":"epmd","protocol":"TCP"},{"containerPort":25672,"name":"inter-node","protocol":"TCP"}],"resources":{"limits":{"cpu":"1000m","memory":"2Gi"},"requests":{"cpu":"100m","memory":"256Mi"}},"volumeMounts":[{"mountPath":"/etc/rabbitmq","name":"config","readOnly":true},{"mountPath":"/var/lib/rabbitmq","name":"data"},{"mountPath":"/var/log/rabbitmq","name":"logs"}]}],"initContainers":[{"command":["sh","-c","chown -R 999:999 /var/lib/rabbitmq /var/log/rabbitmq\nchmod -R 775 /var/lib/rabbitmq /var/log/rabbitmq\n"],"image":"busybox","name":"fix-permissions","securityContext":{"runAsUser":0},"volumeMounts":[{"mountPath":"/var/lib/rabbitmq","name":"data"},{"mountPath":"/var/log/rabbitmq","name":"logs"}]}],"securityContext":{"fsGroup":999,"runAsGroup":999,"runAsNonRoot":true,"runAsUser":999},"serviceAccountName":"rabbitmq","subdomain":"rabbitmq-headless","terminationGracePeriodSeconds":120,"volumes":[{"configMap":{"defaultMode":420,"items":[{"key":"rabbitmq.conf","path":"rabbitmq.conf"},{"key":"enabled_plugins","path":"enabled_plugins"}],"name":"rabbitmq-config"},"name":"config"},{"emptyDir":{},"name":"ssl-certs"},{"emptyDir":{},"name":"data"},{"emptyDir":{},"name":"logs"}]}}}}
  creationTimestamp: "2025-11-09T20:34:33Z"
  generation: 5
  labels:
    app.kubernetes.io/component: messaging
    app.kubernetes.io/name: rabbitmq
  name: rabbitmq
  namespace: rabbitmq
  resourceVersion: "15697"
  uid: 8007bd1d-1c27-419f-9471-fb55166cc24d
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  podManagementPolicy: OrderedReady
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: rabbitmq
  serviceName: rabbitmq-headless
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-11-09T20:47:42Z"
        prometheus.io/path: /metrics
        prometheus.io/port: "15692"
        prometheus.io/scrape: "true"
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: messaging
        app.kubernetes.io/name: rabbitmq
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                  - rabbitmq
              topologyKey: kubernetes.io/hostname
            weight: 100
      containers:
      - env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: RABBITMQ_DEFAULT_USER
          valueFrom:
            secretKeyRef:
              key: username
              name: rabbitmq-admin
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              key: password
              name: rabbitmq-admin
        - name: RABBITMQ_ERLANG_COOKIE
          valueFrom:
            secretKeyRef:
              key: cookie
              name: rabbitmq-admin
        - name: RABBITMQ_USE_LONGNAME
          value: "true"
        - name: K8S_SERVICE_NAME
          value: rabbitmq-headless
        - name: RABBITMQ_ENABLED_PLUGINS_FILE
          value: /etc/rabbitmq/enabled_plugins
        - name: RABBITMQ_CONFIG_FILE
          value: /etc/rabbitmq/rabbitmq.conf
        - name: RABBITMQ_LOGS
          value: /var/log/rabbitmq/rabbitmq.log
        - name: RABBITMQ_SASL_LOGS
          value: /var/log/rabbitmq/rabbitmq-sasl.log
        image: rabbitmq:3.12.12-management-alpine
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command:
              - rabbitmqctl
              - stop_app
        name: rabbitmq
        ports:
        - containerPort: 5672
          name: amqp
          protocol: TCP
        - containerPort: 5671
          name: amqp-ssl
          protocol: TCP
        - containerPort: 15672
          name: management
          protocol: TCP
        - containerPort: 15671
          name: management-ssl
          protocol: TCP
        - containerPort: 15692
          name: prometheus
          protocol: TCP
        - containerPort: 15691
          name: prometheus-ssl
          protocol: TCP
        - containerPort: 4369
          name: epmd
          protocol: TCP
        - containerPort: 25672
          name: inter-node
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: 100m
            memory: 256Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/rabbitmq
          name: config
          readOnly: true
        - mountPath: /var/lib/rabbitmq
          name: data
        - mountPath: /var/log/rabbitmq
          name: logs
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 999
        runAsGroup: 999
        runAsNonRoot: true
        runAsUser: 999
      serviceAccount: rabbitmq
      serviceAccountName: rabbitmq
      subdomain: rabbitmq-headless
      terminationGracePeriodSeconds: 120
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: rabbitmq.conf
            path: rabbitmq.conf
          - key: enabled_plugins
            path: enabled_plugins
          name: rabbitmq-config
        name: config
      - emptyDir: {}
        name: ssl-certs
      - emptyDir: {}
        name: data
      - emptyDir: {}
        name: logs
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
status:
  availableReplicas: 3
  collisionCount: 0
  currentReplicas: 3
  currentRevision: rabbitmq-8478dd5689
  observedGeneration: 5
  readyReplicas: 3
  replicas: 3
  updateRevision: rabbitmq-8478dd5689
  updatedReplicas: 3
