apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: n8n-tls
  namespace: n8n
spec:
  secretName: n8n-tls
  duration: 8760h
  renewBefore: 720h
  dnsNames:
  - n8n.home.arpa
  issuerRef:
    kind: ClusterIssuer
    name: local-ca
