apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin
  namespace: monitoring
type: Opaque
stringData:
  GF_SECURITY_ADMIN_USER: "admin"
  GF_SECURITY_ADMIN_PASSWORD: "<YOUR_GRAFANA_ADMIN_PASSWORD>" # ALTERE ESTA SENHA! Use uma senha forte.
