apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-tls
  namespace: monitoring
spec:
  secretName: grafana-tls
  dnsNames:
  - grafana.home.arpa
  issuerRef:
    kind: ClusterIssuer
    name: local-ca
