apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prometheus-tls
  namespace: monitoring
spec:
  secretName: prometheus-tls
  dnsNames:
  - prometheus.home.arpa
  issuerRef:
    kind: ClusterIssuer
    name: local-ca
