---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: observability-stack-alerts
  namespace: monitoring
  labels:
    app: prometheus
    role: alert-rules
spec:
  groups:
    # Alertas para Loki
    - name: loki.rules
      rules:
        - alert: LokiDown
          expr: up{job="loki"} == 0
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: "Loki está indisponível"
            description: "Loki não está respondendo há mais de 5 minutos."
        
        - alert: LokiHighIngestionRate
          expr: rate(loki_distributor_ingester_appends_total[5m]) > 1000
          for: 10m
          labels:
            severity: warning
          annotations:
            summary: "Taxa de ingestão alta no Loki"
            description: "Loki está recebendo mais de 1000 logs por segundo há mais de 10 minutos."
        
        - alert: LokiStorageSpaceRunningOut
          expr: (node_filesystem_avail_bytes{mountpoint="/var/loki"} / node_filesystem_size_bytes{mountpoint="/var/loki"}) * 100 < 10
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "Espaço de armazenamento do Loki baixo"
            description: "Menos de 10% de espaço livre no armazenamento do Loki."
    
    # Alertas para Mimir
    - name: mimir.rules
      rules:
        - alert: MimirDown
          expr: up{job="mimir"} == 0
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: "Mimir está indisponível"
            description: "Mimir não está respondendo há mais de 5 minutos."
        
        - alert: MimirHighIngestionRate
          expr: rate(cortex_distributor_received_samples_total[5m]) > 10000
          for: 10m
          labels:
            severity: warning
          annotations:
            summary: "Taxa de ingestão alta no Mimir"
            description: "Mimir está recebendo mais de 10000 amostras por segundo há mais de 10 minutos."
        
        - alert: MimirCompactionFailing
          expr: increase(cortex_compactor_runs_failed_total[1h]) > 0
          for: 30m
          labels:
            severity: warning
          annotations:
            summary: "Falha na compactação do Mimir"
            description: "Mimir teve falhas na compactação na última hora."
    
    # Alertas para Tempo
    - name: tempo.rules
      rules:
        - alert: TempoDown
          expr: up{job="tempo"} == 0
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: "Tempo está indisponível"
            description: "Tempo não está respondendo há mais de 5 minutos."
        
        - alert: TempoHighIngestionRate
          expr: rate(tempo_distributor_spans_received_total[5m]) > 1000
          for: 10m
          labels:
            severity: warning
          annotations:
            summary: "Taxa de ingestão alta no Tempo"
            description: "Tempo está recebendo mais de 1000 spans por segundo há mais de 10 minutos."
        
        - alert: TempoStorageSpaceRunningOut
          expr: (node_filesystem_avail_bytes{mountpoint="/var/tempo"} / node_filesystem_size_bytes{mountpoint="/var/tempo"}) * 100 < 10
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "Espaço de armazenamento do Tempo baixo"
            description: "Menos de 10% de espaço livre no armazenamento do Tempo."
    
    # Alertas para Pyroscope
    - name: pyroscope.rules
      rules:
        - alert: PyroscopeDown
          expr: up{job="pyroscope"} == 0
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: "Pyroscope está indisponível"
            description: "Pyroscope não está respondendo há mais de 5 minutos."
        
        - alert: PyroscopeHighIngestionRate
          expr: rate(pyroscope_ingest_samples_total[5m]) > 1000
          for: 10m
          labels:
            severity: warning
          annotations:
            summary: "Taxa de ingestão alta no Pyroscope"
            description: "Pyroscope está recebendo mais de 1000 amostras de profiling por segundo há mais de 10 minutos."
        
        - alert: PyroscopeStorageSpaceRunningOut
          expr: (node_filesystem_avail_bytes{mountpoint="/var/lib/pyroscope"} / node_filesystem_size_bytes{mountpoint="/var/lib/pyroscope"}) * 100 < 10
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "Espaço de armazenamento do Pyroscope baixo"
            description: "Menos de 10% de espaço livre no armazenamento do Pyroscope."
    
    # Alertas gerais para o stack de observabilidade
    - name: observability-stack.rules
      rules:
        - alert: ObservabilityStackHighMemoryUsage
          expr: (container_memory_working_set_bytes{namespace="monitoring"} / container_spec_memory_limit_bytes{namespace="monitoring"}) * 100 > 80
          for: 10m
          labels:
            severity: warning
          annotations:
            summary: "Alto uso de memória no stack de observabilidade"
            description: "Container {{ $labels.container }} no namespace monitoring está usando mais de 80% da memória alocada."
        
        - alert: ObservabilityStackHighCPUUsage
          expr: (rate(container_cpu_usage_seconds_total{namespace="monitoring"}[5m]) / container_spec_cpu_quota{namespace="monitoring"} * container_spec_cpu_period{namespace="monitoring"}) * 100 > 80
          for: 10m
          labels:
            severity: warning
          annotations:
            summary: "Alto uso de CPU no stack de observabilidade"
            description: "Container {{ $labels.container }} no namespace monitoring está usando mais de 80% da CPU alocada."