apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: coder-tls
  namespace: coder
spec:
  secretName: coder-tls
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
  commonName: coder.home.arpa
  dnsNames:
    - coder.home.arpa
    - "*.coder.home.arpa"
  duration: 8760h # 1 ano
  renewBefore: 720h # 30 dias antes