apiVersion: v1
kind: Secret
metadata:
  name: authentik-secrets
  namespace: authentik
type: Opaque
stringData:
  AUTHENTIK_SECRET_KEY: "ffKai6Hd5+Q16ZOiPAA7TWZ3dV3lmyNIQfK+stfI+7eKRzRO"
  AUTHENTIK_POSTGRESQL__PASSWORD: "Admin@123"
  AUTHENTIK_POSTGRESQL__USER: "admin_db"
  AUTHENTIK_REDIS__PASSWORD: "Admin@123"
