apiVersion: v1
kind: Namespace
metadata:
  name: rabbitmq
  labels:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/component: messaging
    app.kubernetes.io/part-of: infrastructure
    name: rabbitmq
  annotations:
    scheduler.alpha.kubernetes.io/node-selector: ""
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: rabbitmq-quota
  namespace: rabbitmq
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    persistentvolumeclaims: "10"
    services: "10"
    secrets: "20"
    configmaps: "10"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: rabbitmq-limits
  namespace: rabbitmq
spec:
  limits:
  - default:
      cpu: 1000m
      memory: 2Gi
    defaultRequest:
      cpu: 100m
      memory: 256Mi
    type: Container
  - min:
      storage: 1Gi
    max:
      storage: 10Gi
    type: PersistentVolumeClaim