apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-admin
  namespace: rabbitmq
  labels:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/component: messaging
type: Opaque
stringData:
  username: admin
  password: Admin@123
  cookie: "ERLANG_COOKIE_2024_RABBITMQ_CLUSTER_SECURE_RANDOM_STRING"
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-app
  namespace: rabbitmq
  labels:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/component: messaging
type: Opaque
stringData:
  username: appuser
  password: Admin@123
  vhost: "/"
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-monitoring
  namespace: rabbitmq
  labels:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/component: monitoring
type: Opaque
stringData:
  prometheus_user: prometheus
  prometheus_password: Admin@123
  grafana_user: grafana
  grafana_password: Admin@123