apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-nodeport
  namespace: rabbitmq
  labels:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/component: messaging
spec:
  type: NodePort
  ports:
  - name: amqp
    port: 5672
    targetPort: amqp
    protocol: TCP
    nodePort: 30672
  - name: amqp-ssl
    port: 5671
    targetPort: amqp-ssl
    protocol: TCP
    nodePort: 30671
  - name: management
    port: 15672
    targetPort: management
    protocol: TCP
    nodePort: 31672
  - name: management-ssl
    port: 15671
    targetPort: management-ssl
    protocol: TCP
    nodePort: 31671
  selector:
    app.kubernetes.io/name: rabbitmq