apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
  namespace: rabbitmq
  labels:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/component: messaging
spec:
  serviceName: rabbitmq-headless
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: rabbitmq
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rabbitmq
        app.kubernetes.io/component: messaging
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "15692"
        prometheus.io/path: "/metrics"
    spec:
      subdomain: rabbitmq-headless
      serviceAccountName: rabbitmq
      terminationGracePeriodSeconds: 120
      securityContext:
        fsGroup: 999
        runAsUser: 999
        runAsGroup: 999
      initContainers:
      - name: fix-permissions
        image: busybox:1.36
        command:
          - sh
          - -c
          - |
            set -e
            echo "Fixing permissions..."
            chown -R 999:999 /var/lib/rabbitmq /var/log/rabbitmq
            chmod -R 755 /var/lib/rabbitmq /var/log/rabbitmq

            # Create .erlang.cookie with correct permissions if it doesn't exist
            COOKIE_FILE="/var/lib/rabbitmq/.erlang.cookie"
            if [ ! -f "$COOKIE_FILE" ]; then
              echo "Creating .erlang.cookie..."
              echo "$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)" > "$COOKIE_FILE"
            fi

            # Ensure correct ownership and permissions for .erlang.cookie
            chown 999:999 "$COOKIE_FILE"
            chmod 400 "$COOKIE_FILE"

            echo "Permissions fixed successfully"
            ls -la /var/lib/rabbitmq/
        securityContext:
          runAsUser: 0
        volumeMounts:
          - name: data
            mountPath: /var/lib/rabbitmq
          - name: logs
            mountPath: /var/log/rabbitmq
      containers:
      - name: rabbitmq
        image: rabbitmq:3.12.12-management-alpine
        imagePullPolicy: IfNotPresent
        
        ports:
        - name: amqp
          containerPort: 5672
          hostPort: 5672  # Expor diretamente no host para evitar problemas de LoadBalancer/IPTables
          protocol: TCP
        - name: amqp-ssl
          containerPort: 5671
          protocol: TCP
        - name: management
          containerPort: 15672
          protocol: TCP
        - name: management-ssl
          containerPort: 15671
          protocol: TCP
        - name: prometheus
          containerPort: 15692
          protocol: TCP
        - name: prometheus-ssl
          containerPort: 15691
          protocol: TCP
        - name: epmd
          containerPort: 4369
          protocol: TCP
        - name: inter-node
          containerPort: 25672
          protocol: TCP
        
        env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: RABBITMQ_DEFAULT_USER
          valueFrom:
            secretKeyRef:
              name: rabbitmq-admin
              key: username
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: rabbitmq-admin
              key: password
        - name: RABBITMQ_ERLANG_COOKIE
          valueFrom:
            secretKeyRef:
              name: rabbitmq-admin
              key: cookie
        - name: RABBITMQ_USE_LONGNAME
          value: "true"
        - name: K8S_SERVICE_NAME
          value: "rabbitmq-headless"
        - name: RABBITMQ_ENABLED_PLUGINS_FILE
          value: "/etc/rabbitmq/enabled_plugins"
        - name: RABBITMQ_LOGS
          value: "-"
        - name: RABBITMQ_SASL_LOGS
          value: "-"
        
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 2Gi
        

        
        # Startup probe desabilitado temporariamente em homelab para evitar reinícios
        # startupProbe:
        #   exec:
        #     command:
        #     - sh
        #     - -ec
        #     - rabbitmq-diagnostics -q ping
        #   initialDelaySeconds: 90
        #   timeoutSeconds: 10
        #   periodSeconds: 10
        #   successThreshold: 1
        #   failureThreshold: 60
        
        volumeMounts:
        - name: config
          mountPath: /etc/rabbitmq
          readOnly: true
        - name: data
          mountPath: /var/lib/rabbitmq
        - name: logs
          mountPath: /var/log/rabbitmq
        
        lifecycle:
          preStop:
            exec:
              command:
              - rabbitmqctl
              - stop_app
      
      volumes:
      - name: config
        configMap:
          name: rabbitmq-config
          items:
          - key: rabbitmq.conf
            path: rabbitmq.conf
          - key: enabled_plugins
            path: enabled_plugins
          defaultMode: 0644
      - name: ssl-certs
        # TLS mount removido em homelab para simplificar
        emptyDir: {}

      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                  - rabbitmq
              topologyKey: kubernetes.io/hostname

  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: local-path  # K3s default StorageClass
      resources:
        requests:
          storage: 10Gi
  - metadata:
      name: logs
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: local-path
      resources:
        requests:
          storage: 2Gi
