apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-basic-auth
  namespace: rabbitmq
  labels:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/component: management
type: Opaque
data:
  auth: YWRtaW46JGFwcjEkSDY1dnpwTm8kOVhTQ1N1M0R6QzE1d0l0LlF1VDFELg== # admin:rabbitmq-admin-2024!