apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: rabbitmqclusters.rabbitmq.com
  labels:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/component: crd
spec:
  group: rabbitmq.com
  versions:
  - name: v1beta1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              replicas:
                type: integer
                minimum: 1
                maximum: 7
                default: 3
              image:
                type: string
                default: "rabbitmq:3.12.12-management-alpine"
              resources:
                type: object
                properties:
                  requests:
                    type: object
                    properties:
                      cpu:
                        type: string
                        default: "500m"
                      memory:
                        type: string
                        default: "1Gi"
                  limits:
                    type: object
                    properties:
                      cpu:
                        type: string
                        default: "1"
                      memory:
                        type: string
                        default: "2Gi"
              storage:
                type: object
                properties:
                  size:
                    type: string
                    default: "10Gi"
                  storageClassName:
                    type: string
                    default: "local-path"
              tls:
                type: object
                properties:
                  enabled:
                    type: boolean
                    default: true
                  secretName:
                    type: string
                    default: "rabbitmq-tls"
              monitoring:
                type: object
                properties:
                  enabled:
                    type: boolean
                    default: true
                  prometheusPort:
                    type: integer
                    default: 15692
              persistence:
                type: object
                properties:
                  enabled:
                    type: boolean
                    default: true
                  storageClass:
                    type: string
                    default: "local-path"
              highAvailability:
                type: object
                properties:
                  enabled:
                    type: boolean
                    default: true
                  mode:
                    type: string
                    enum: ["autoheal", "pause_minority", "ignore"]
                    default: "pause_minority"
          status:
            type: object
            properties:
              phase:
                type: string
                enum: ["Pending", "Creating", "Running", "Failed"]
              conditions:
                type: array
                items:
                  type: object
                  properties:
                    type:
                      type: string
                    status:
                      type: string
                    lastTransitionTime:
                      type: string
                    reason:
                      type: string
                    message:
                      type: string
              nodes:
                type: array
                items:
                  type: string
              readyNodes:
                type: integer
              clusterSize:
                type: integer
    subresources:
      status: {}
      scale:
        specReplicasPath: .spec.replicas
        statusReplicasPath: .status.clusterSize
  scope: Namespaced
  names:
    plural: rabbitmqclusters
    singular: rabbitmqcluster
    kind: RabbitMQCluster
    shortNames:
    - rmq
---
apiVersion: rabbitmq.com/v1beta1
kind: RabbitMQCluster
metadata:
  name: rabbitmq-cluster
  namespace: rabbitmq
  labels:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/component: cluster
spec:
  replicas: 3
  image: "rabbitmq:3.12.12-management-alpine"
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "1"
      memory: "2Gi"
  storage:
    size: "10Gi"
    storageClassName: "local-path"
  tls:
    enabled: true
    secretName: "rabbitmq-tls"
  monitoring:
    enabled: true
    prometheusPort: 15692
  persistence:
    enabled: true
    storageClass: "local-path"
  highAvailability:
    enabled: true
    mode: "pause_minority"