apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: redis-stats-tls
  namespace: redis
spec:
  secretName: redis-stats-tls
  issuerRef:
    name: local-ca
    kind: ClusterIssuer
  commonName: redis-stats.home.arpa
  dnsNames:
  - redis-stats.home.arpa