apiVersion: v1
data:
  enabled_plugins: |
    [rabbitmq_management,rabbitmq_management_agent,rabbitmq_web_dispatch,rabbitmq_prometheus,rabbitmq_peer_discovery_k8s].
  rabbitmq.conf: |
    ## Core Configuration
    listeners.tcp.default = 5672
    management.tcp.port = 15672

    ## Clustering
    cluster_formation.peer_discovery_backend = rabbit_peer_discovery_k8s
    cluster_formation.k8s.host = kubernetes.default.svc.cluster.local
    cluster_formation.k8s.address_type = hostname
    cluster_formation.node_cleanup.interval = 30
    cluster_formation.node_cleanup.only_log_warning = true
    cluster_partition_handling = autoheal

    ## Memory and Disk Thresholds
    vm_memory_high_watermark.relative = 0.6
    disk_free_limit.absolute = 2GB

    ## Logging
    log.console = true
    log.console.level = info
    log.file.level = info
    log.file = /var/log/rabbitmq/rabbitmq.log

    ## Prometheus Metrics
    prometheus.tcp.port = 15692

    ## SSL/TLS disabled for homelab

    ## Management Plugin
    management.cors.allow_origins.1 = *
    management.cors.allow_origins.2 = http://localhost:3000

    ## Queue Configuration
    queue_master_locator = min-masters

    ## High Availability
    cluster_keepalive_interval = 10000
    net_ticktime = 60
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"enabled_plugins":"[rabbitmq_management,rabbitmq_management_agent,rabbitmq_web_dispatch,rabbitmq_prometheus,rabbitmq_peer_discovery_k8s].\n","rabbitmq.conf":"## Core Configuration\nlisteners.tcp.default = 5672\nmanagement.tcp.port = 15672\n\n## Clustering\ncluster_formation.peer_discovery_backend = rabbit_peer_discovery_k8s\ncluster_formation.k8s.host = kubernetes.default.svc.cluster.local\ncluster_formation.k8s.address_type = hostname\ncluster_formation.node_cleanup.interval = 30\ncluster_formation.node_cleanup.only_log_warning = true\ncluster_partition_handling = autoheal\n\n## Memory and Disk Thresholds\nvm_memory_high_watermark.relative = 0.6\ndisk_free_limit.absolute = 2GB\n\n## Logging\nlog.console = true\nlog.console.level = info\nlog.file.level = info\nlog.file = /var/log/rabbitmq/rabbitmq.log\n\n## Prometheus Metrics\nprometheus.tcp.port = 15692\n\n## SSL/TLS disabled for homelab\n\n## Management Plugin\nmanagement.cors.allow_origins.1 = *\nmanagement.cors.allow_origins.2 = http://localhost:3000\n\n## Queue Configuration\nqueue_master_locator = min-masters\n\n## High Availability\ncluster_keepalive_interval = 10000\nnet_ticktime = 60\n"},"kind":"ConfigMap","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"messaging","app.kubernetes.io/name":"rabbitmq"},"name":"rabbitmq-config","namespace":"rabbitmq"}}
  creationTimestamp: "2025-11-09T20:44:55Z"
  labels:
    app.kubernetes.io/component: messaging
    app.kubernetes.io/name: rabbitmq
  name: rabbitmq-config
  namespace: rabbitmq
  resourceVersion: "2164"
  uid: 7b9daa87-b30e-45de-a085-32c63de3e942
