apiVersion: v1
kind: Service
metadata:
  name: mongodb-client
  namespace: mongodb
  labels:
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/component: database
spec:
  type: LoadBalancer
  ports:
    - name: mongodb
      port: 27017
      targetPort: 27017
      protocol: TCP
  selector:
    app.kubernetes.io/name: mongodb
