apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
  namespace: mongodb
  labels:
    app.kubernetes.io/name: mongo-express
    app.kubernetes.io/component: management
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mongo-express
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mongo-express
        app.kubernetes.io/component: management
    spec:
      containers:
      - name: mongo-express
        image: mongo-express:1.0.0-alpha.4
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8081
          name: http
        env:
        - name: ME_CONFIG_MONGODB_SERVER
          value: "mongodb-client"
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-creds
              key: mongo-root-username
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-creds
              key: mongo-root-password-url-encoded
        - name: ME_CONFIG_BASICAUTH_USERNAME
          value: "admin"
        - name: ME_CONFIG_BASICAUTH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-creds
              key: mongo-root-password
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          tcpSocket:
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express
  namespace: mongodb
  labels:
    app.kubernetes.io/name: mongo-express
    app.kubernetes.io/component: management
spec:
  type: ClusterIP
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: mongo-express

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mongodb-console-tls
  namespace: mongodb
spec:
  secretName: mongodb-console-tls
  duration: 8760h
  renewBefore: 720h
  dnsNames:
  - mongodb-console.home.arpa
  issuerRef:
    kind: ClusterIssuer
    name: local-ca

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mongo-express-ingress
  namespace: mongodb
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: local-ca
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - mongodb-console.home.arpa
    secretName: mongodb-console-tls
  rules:
  - host: mongodb-console.home.arpa
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mongo-express
            port:
              number: 8081
