# Security Context para pods com restrições elevadas
apiVersion: v1
kind: SecurityContext
metadata:
  name: restricted-security-context
runAsNonRoot: true
runAsUser: 65534
runAsGroup: 65534
fsGroup: 65534
seccompProfile:
  type: RuntimeDefault
capabilities:
  drop:
    - ALL
readOnlyRootFilesystem: true
allowPrivilegeEscalation: false