apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-tls
  namespace: argocd
spec:
  secretName: argocd-tls
  dnsNames:
  - argocd.home.arpa
  issuerRef:
    kind: ClusterIssuer
    name: local-ca
