apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kibana-tls
  namespace: elk
spec:
  secretName: kibana-tls
  issuerRef:
    name: local-ca
    kind: ClusterIssuer
  dnsNames:
    - kibana.home.arpa