apiVersion: v1
kind: Secret
metadata:
  name: kong-auth
  namespace: kong
type: Opaque
stringData:
  KONG_USER: "admin"
  KONG_PASSWORD: "Admin@123"
---
# Secret para Basic Auth no Ingress (admin:Admin@123)
# Gerado via: htpasswd -nb admin Admin@123 | base64
apiVersion: v1
kind: Secret
metadata:
  name: kong-admin-auth
  namespace: kong
type: Opaque
data:
  auth: YWRtaW46JGFwcDEkcm93S0p5dUMkUzhWUWx0N0x6V1d6M0p5T3p2TUZuMAo=
