apiVersion: v1
kind: LimitRange
metadata:
  name: resource-limits
  namespace: default
spec:
  limits:
  - default:
      cpu: 1000m
      memory: 1Gi
    defaultRequest:
      cpu: 100m
      memory: 128Mi
    type: Container
  - default:
      storage: 10Gi
    type: PersistentVolumeClaim

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota
  namespace: default
spec:
  hard:
    requests.cpu: "10"
    requests.memory: 20Gi
    limits.cpu: "20"
    limits.memory: 40Gi
    persistentvolumeclaims: "10"
    services.loadbalancers: "2"
    services.nodeports: "5"
    count/pods: "50"
    count/services: "20"
    count/secrets: "50"
    count/configmaps: "50"
    count/persistentvolumeclaims: "10"

---
apiVersion: v1
kind: LimitRange
metadata:
  name: resource-limits-monitoring
  namespace: monitoring
spec:
  limits:
  - default:
      cpu: 500m
      memory: 1Gi
    defaultRequest:
      cpu: 100m
      memory: 256Mi
    type: Container

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota-monitoring
  namespace: monitoring
spec:
  hard:
    requests.cpu: "5"
    requests.memory: 10Gi
    limits.cpu: "10"
    limits.memory: 20Gi
    count/pods: "20"
    count/services: "10"
    count/secrets: "20"
    count/configmaps: "20"

---
apiVersion: v1
kind: LimitRange
metadata:
  name: resource-limits-production
  namespace: production
spec:
  limits:
  - default:
      cpu: 1000m
      memory: 2Gi
    defaultRequest:
      cpu: 200m
      memory: 512Mi
    type: Container

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota-production
  namespace: production
spec:
  hard:
    requests.cpu: "50"
    requests.memory: 100Gi
    limits.cpu: "100"
    limits.memory: 200Gi
    persistentvolumeclaims: "50"
    services.loadbalancers: "10"
    services.nodeports: "10"
    count/pods: "100"
    count/services: "50"
    count/secrets: "100"
    count/configmaps: "100"
    count/persistentvolumeclaims: "50"