# Certificados TLS para Redis usando cert-manager
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: redis-selfsigned-ca-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: redis-ca-key-pair
  namespace: redis
spec:
  isCA: true
  commonName: redis-ca
  secretName: redis-ca-key-pair
  issuerRef:
    name: redis-selfsigned-ca-issuer
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: redis-ca-issuer
  namespace: redis
spec:
  ca:
    secretName: redis-ca-key-pair
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: redis-server-cert
  namespace: redis
spec:
  secretName: redis-tls-secret
  issuerRef:
    name: redis-ca-issuer
    kind: Issuer
  commonName: redis-master.redis.svc.cluster.local
  dnsNames:
  - redis-master
  - redis-master.redis
  - redis-master.redis.svc
  - redis-master.redis.svc.cluster.local
  - redis-replica-0.redis-replica-headless.redis.svc.cluster.local
  - redis-replica-1.redis-replica-headless.redis.svc.cluster.local
  - redis-replica-2.redis-replica-headless.redis.svc.cluster.local
  - localhost
  ipAddresses:
  - 127.0.0.1