apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-performance-tuning
  namespace: rabbitmq
  labels:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/component: performance-tuning
data:
  performance.conf: |
    # RabbitMQ Performance Tuning Configuration
    # This file contains performance optimizations for high-throughput scenarios
    
    # Memory Management
    vm_memory_high_watermark.relative = 0.6
    vm_memory_high_watermark_paging_ratio = 0.5
    
    # TCP Socket Options
    tcp_listen_options.backlog = 128
    tcp_listen_options.nodelay = true
    tcp_listen_options.linger.on = true
    tcp_listen_options.linger.timeout = 0
    tcp_listen_options.sndbuf = 196608
    tcp_listen_options.recbuf = 196608
    
    # Connection Limits
    num_acceptors.tcp = 10
    num_acceptors.ssl = 1
    handshake_timeout = 10000
    heartbeat = 60
    
    # Channel Limits
    channel_max = 2047
    
    # Queue Performance
    queue_master_locator = min-masters
    queue_index_embed_msgs_below = 4096
    queue_index_max_journal_entries = 32768
    
    # Message Store
    msg_store_file_size_limit = 16777216
    msg_store_index_module = rabbit_msg_store_ets_index
    
    # File Handle Cache
    file_handle_cache_size = 32768
    
    # Disk Monitoring
    disk_free_limit.absolute = 1GB
    disk_monitor_failure_retries = 10
    disk_monitor_failure_retry_interval = 120000
    
    # Background GC
    background_gc_enabled = true
    background_gc_target_interval = 60000
    
    # Mnesia Configuration
    mnesia_table_loading_timeout = 30000
    mnesia_schema_cleanup_interval = 300000
    
    # Log Level (reduce for performance)
    log.console.level = warning
    log.file.level = warning
    
  high-throughput.conf: |
    # High Throughput Configuration
    # Use this for scenarios requiring maximum message throughput
    
    # Disable unnecessary features
    management.load_definitions = none
    management.rates_mode = none
    
    # Optimize for throughput
    queue_master_locator = client-local
    queue_index_embed_msgs_below = 8192
    queue_index_max_journal_entries = 65536
    
    # Increase TCP buffers
    tcp_listen_options.sndbuf = 393216
    tcp_listen_options.recbuf = 393216
    
    # Connection pooling
    num_acceptors.tcp = 20
    num_acceptors.ssl = 2
    
    # Message store optimization
    msg_store_file_size_limit = 33554432
    msg_store_credit_disc_bound.credit = 4194304
    msg_store_credit_disc_bound.credit_flow_default_credit = 4194304
    
    # Memory management for high throughput
    vm_memory_high_watermark.relative = 0.8
    vm_memory_high_watermark_paging_ratio = 0.75
    
  low-latency.conf: |
    # Low Latency Configuration
    # Use this for scenarios requiring minimal message latency
    
    # Optimize for low latency
    queue_master_locator = client-local
    queue_index_embed_msgs_below = 1024
    queue_index_max_journal_entries = 8192
    
    # Reduce TCP buffers for lower latency
    tcp_listen_options.sndbuf = 65536
    tcp_listen_options.recbuf = 65536
    
    # Faster heartbeats
    heartbeat = 30
    
    # Connection limits for low latency
    num_acceptors.tcp = 5
    num_acceptors.ssl = 1
    
    # Memory management for low latency
    vm_memory_high_watermark.relative = 0.4
    vm_memory_high_watermark_paging_ratio = 0.3
    
    # Disable background GC for consistent latency
    background_gc_enabled = false
    
  balanced.conf: |
    # Balanced Configuration (Default)
    # Good balance between throughput and latency
    
    # Balanced queue configuration
    queue_master_locator = min-masters
    queue_index_embed_msgs_below = 4096
    queue_index_max_journal_entries = 32768
    
    # Balanced TCP configuration
    tcp_listen_options.sndbuf = 196608
    tcp_listen_options.recbuf = 196608
    
    # Balanced connection limits
    num_acceptors.tcp = 10
    num_acceptors.ssl = 1
    
    # Balanced memory management
    vm_memory_high_watermark.relative = 0.6
    vm_memory_high_watermark_paging_ratio = 0.5
    
    # Balanced heartbeat
    heartbeat = 60
    
    # Enable background GC
    background_gc_enabled = true
    background_gc_target_interval = 60000