apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-prometheus
  namespace: rabbitmq
  labels:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/component: monitoring
spec:
  type: ClusterIP
  ports:
  - name: prometheus
    port: 15692
    targetPort: prometheus
    protocol: TCP
  - name: prometheus-ssl
    port: 15691
    targetPort: prometheus-ssl
    protocol: TCP
  selector:
    app.kubernetes.io/name: rabbitmq
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rabbitmq
  namespace: rabbitmq
  labels:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/component: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: rabbitmq
      app.kubernetes.io/component: monitoring
  endpoints:
  - port: prometheus
    interval: 30s
    path: /metrics
    scheme: http
    scrapeTimeout: 10s
    params:
      family:
      - queue_coarse_metrics
      - queue_metrics
      - connection_channe_metrics
      - connection_metrics
      - node_metrics
  - port: prometheus-ssl
    interval: 30s
    path: /metrics
    scheme: https
    scrapeTimeout: 10s
    tlsConfig:
      insecureSkipVerify: true
    params:
      family:
      - queue_coarse_metrics
      - queue_metrics
      - connection_channe_metrics
      - connection_metrics
      - node_metrics
  namespaceSelector:
    matchNames:
    - rabbitmq