# Service interno; o acesso externo virá pelo Ingress
service:
  type: ClusterIP
  port: 80

# Variáveis de ambiente do container "coder"
env:
  # URL pública que os agentes/workspaces usarão
  - name: CODER_ACCESS_URL
    value: "https://coder.seu-dominio.com"

  # Injeta a URL do Postgres do Secret coder-db-url
  - name: CODER_PG_CONNECTION_URL
    valueFrom:
      secretKeyRef:
        name: coder-db-url
        key: url

  # (Opcional) desativar telemetria
  - name: CODER_TELEMETRY_ENABLE
    value: "false"

# Recursos (ajuste conforme seu cluster)
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: "1"
    memory: 1Gi

# Probes (os defaults do chart costumam ser ok; aqui vai um exemplo)
livenessProbe:
  httpGet:
    path: /healthz
    port: http
  initialDelaySeconds: 20
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /healthz
    port: http
  initialDelaySeconds: 10
  periodSeconds: 10