apiVersion: v1
kind: Service
metadata:
  name: redis-cluster-headless
  namespace: redis
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: redis-cluster
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
  - name: cluster-bus
    port: 16379
    targetPort: 16379
