apiVersion: v1
kind: Service
metadata:
  name: redis-cluster
  namespace: redis
spec:
  selector:
    app: redis-cluster
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
  type: ClusterIP
