# Proxy HAProxy para Redis com Terminação TLS
# Este proxy permite acesso externo ao Redis sem necessidade de certificados no cliente
# O proxy faz a terminação TLS e conecta ao Redis internamente com TLS

apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-proxy-config
  namespace: redis
data:
  haproxy.cfg: |
    global
        daemon
        log stdout local0 info
        maxconn 4096
        ssl-default-bind-ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384
        ssl-default-bind-options no-sslv3 no-tlsv10 no-tlsv11
        tune.ssl.default-dh-param 2048

    defaults
        mode tcp
        log global
        option tcplog
        option dontlognull
        retries 3
        timeout connect 5000ms
        timeout client 50000ms
        timeout server 50000ms

    # Frontend para conexões externas com TLS - Master para escrita
    frontend redis_tls_frontend
        bind *:6380 ssl crt /etc/ssl/certs/redis-proxy.pem ssl-min-ver TLSv1.2
        default_backend redis_backend

    # Frontend para leitura com TLS e balanceamento entre réplicas
    frontend redis_read_tls_frontend
        bind *:6382 ssl crt /etc/ssl/certs/redis-proxy.pem ssl-min-ver TLSv1.2
        default_backend redis_replica_backend

    # Endpoint de estatísticas para liveness/monitoramento
    listen stats
        bind *:8404
        mode http
        stats enable
        stats uri /stats
        stats refresh 10s
        # auth removido para evitar erro de config; proteja externamente se necessário

    # Backend conectando ao Redis Master com TLS
    backend redis_backend
        balance roundrobin
        server redis-master redis-master.redis.svc.cluster.local:6380 check ssl verify none

    # Backend para réplicas (leitura)
    backend redis_replica_backend
        balance roundrobin
        server redis-replica-0 redis-replica-0.redis-replica-headless.redis.svc.cluster.local:6380 check ssl verify none
        server redis-replica-1 redis-replica-1.redis-replica-headless.redis.svc.cluster.local:6380 check ssl verify none
        server redis-replica-2 redis-replica-2.redis-replica-headless.redis.svc.cluster.local:6380 check ssl verify none



---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: redis-proxy-tls
  namespace: redis
spec:
  secretName: redis-proxy-tls
  dnsNames:
  - redis-proxy.redis.svc.cluster.local
  - redis.home.arpa
  - redis-proxy.home.arpa
  issuerRef:
    kind: Issuer
    name: redis-ca-issuer
---
# Deployment do HAProxy
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-proxy
  namespace: redis
  labels:
    app: redis-proxy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redis-proxy
  template:
    metadata:
      labels:
        app: redis-proxy
    spec:
      initContainers:
      - name: build-pem
        image: alpine:3.19
        command: ["/bin/sh","-c"]
        args:
        - "cat /secrets/tls.crt /secrets/tls.key > /certs/redis-proxy.pem && chmod 644 /certs/redis-proxy.pem"
        volumeMounts:
        - name: tls-certs
          mountPath: /secrets
        - name: pem-certs
          mountPath: /certs
      containers:
      - name: haproxy
        image: haproxy:2.8-alpine
        command: ["haproxy"]
        args: ["-db", "-f", "/usr/local/etc/haproxy/haproxy.cfg"]
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-auth
              key: REDIS_PASSWORD
        - name: HAPROXY_STATS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: haproxy-stats-auth
              key: HAPROXY_STATS_PASSWORD
        ports:
        - containerPort: 6379
          name: redis
        - containerPort: 6380
          name: redis-tls
        - containerPort: 8404
          name: stats
        volumeMounts:
        - name: haproxy-config
          mountPath: /usr/local/etc/haproxy/haproxy.cfg
          subPath: haproxy.cfg
        - name: pem-certs
          mountPath: /etc/ssl/certs
        livenessProbe:
          tcpSocket:
            port: 6380
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 6
        readinessProbe:
          tcpSocket:
            port: 6380
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
      volumes:
      - name: haproxy-config
        configMap:
          name: redis-proxy-config
      - name: tls-certs
        secret:
          secretName: redis-proxy-tls
      - name: pem-certs
        emptyDir: {}

---
# Service para o proxy
apiVersion: v1
kind: Service
metadata:
  name: redis-proxy-service
  namespace: redis
  labels:
    app: redis-proxy
spec:
  type: NodePort
  ports:
  - port: 6380
    targetPort: 6380
    nodePort: 30380
    name: redis-tls
  - port: 6382
    targetPort: 6382
    nodePort: 30382
    name: redis-read-tls
  - port: 8404
    targetPort: 8404
    nodePort: 30404
    name: stats
  selector:
    app: redis-proxy

---
# HorizontalPodAutoscaler para o proxy
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: redis-proxy-hpa
  namespace: redis
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: redis-proxy
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80