apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-tcp
  namespace: ingress
  labels:
    app.kubernetes.io/name: nginx-ingress-microk8s
    app.kubernetes.io/component: tcp-nodeport
spec:
  type: NodePort
  selector:
    name: nginx-ingress-microk8s
  ports:
  - name: amqp
    port: 5672
    targetPort: 5672
    protocol: TCP
  - name: amqp-tls
    port: 5671
    targetPort: 5671
    protocol: TCP
  - name: redis-tls
    port: 6380
    targetPort: 6380
    protocol: TCP
  - name: redis-read-tls
    port: 6382
    targetPort: 6382
    protocol: TCP